baseURL = 'https://blog.pan93.com'
languageCode = 'zh-tw'
defaultContentLanguage = 'zh-tw'
title = 'Pan in the Nutshell'
theme = 'PaperMod'
sectionPagesMenu = 'main'

[params]
description = "Pan in the Nutshell – 分享一些軟體工程和開發的想法 🥰"
author = "pan93412"
ShowPostNavLinks = true
showtoc = true

[params.homeInfoParams]
Title = "Pan in the Nutshell"
Content = "分享一些軟體工程和開發的想法 🥰"

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"

[[params.socialIcons]]
name = "x"
url = "https://x.com/byStarTW"

[[params.socialIcons]]
name = "github"
url = "https://github.com/pan93412"

[[params.socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/pan93412.bsky.social"

[[params.socialIcons]]
name = "mastodon"
url = "https://social.slat.org/@pan93412"

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/pan93412TW"

[[params.socialIcons]]
name = "threads"
url = "https://www.threads.net/pan93412"

[[params.socialIcons]]
name = "email"
url = "mailto:me@pan93.com"

[[params.socialIcons]]
name = "other"
url = "https://pan93.com"

[params.outputs]
home = ['HTML', 'RSS', 'JSON']
